[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  branch = "dev"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"

[[override]]
  name = "github.com/Azure/go-autorest"
  branch = "dev"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.0"
